Dockerfile.openshift
Dockerfile.rhel

`Dockerfile.openshift` and `Dockerfile.rhel` do not include etcdctl binary in the build this PR resolves that.

Dockerfile: add etcdctl

---

Dockerfile.openshift
Dockerfile.rhel

Correcting a typo from 2f109647 (version: openshift-v4.0, 2018-11-29).
CC @hexfusion

Dockerfile.*: Fix "etcd is distributed" -> "etcd is a distributed"

---

Documentation/op-guide/grpc_proxy.md
etcdmain/grpc_proxy.go
etcdserver/api/etcdhttp/metrics.go
proxy/grpcproxy/metrics.go

Cherry pick of #10618 to openshift-4.0
#10618: *: Change gRPC proxy to expose endpoint /metrics
This was originally merged into upstream master and then backported to upstream release-3.3 via https://github.com/etcd-io/etcd/pull/10630
This PR is a fix to https://bugzilla.redhat.com/show_bug.cgi?id=1699045 blocking https://bugzilla.redhat.com/show_bug.cgi?id=1670700
/cc @brancz @s-urbaniak

[cherry-pick openshift-4.0] *: Change gRPC proxy to expose etcd server endpoint /metrics

---

OWNERS

This snuck under the radar because we didn't have approval setup [1].
https://github.com/openshift/etcd/pull/6#issuecomment-482657628

OWNERS: add

---

Dockerfile.openshift
Dockerfile.rhel

Bumping docker to 1.11 for 4.2
This was already bumped in release CI. https://github.com/openshift/release/pull/4321

Dockerfile: bump golang to 1.11

---

Dockerfile.openshift
Dockerfile.rhel

`make build` performs a sanity test on the binary image which causes problems for an unsupported arch. Because we run full CI tests against the image this check is not nessisary and will allow images to be build regardless of arch.
/cc @yselkowitz
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

BUG 1747124: Dockerfile: use build instead of make build

---

Dockerfile.openshift
Dockerfile.rhel

[1 of 2]
This change is 1 of 2 to bump etcd to golang 1.12 which is required for etcd 3.3.15 which we will ship in 4.3

Dockerfile: bump golang 1.12

---

openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go

bug 1805807: create logic for golang ETCD_INITIAL_CLUSTER

---

Dockerfile.openshift
Dockerfile.rhel
build
openshift-tools/discover-etcd-initial-cluster/main.go
openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go

bug 1805809: create logic for golang ETCD_INITIAL_CLUSTER

---

openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go

Bug 1806751: Archive data-dir if target member is unstarted

---

openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go

fixes
```
2020-05-14T04:56:02.740379813Z 2789a93832bcda39, started, nuc4.redpill.nz, https://10.1.10.4:2380, https://10.1.10.4:2379
2020-05-14T04:56:02.740379813Z 5187f12b86fd7087, unstarted, , https://10.1.10.3:2380, 
2020-05-14T04:56:02.740379813Z f374a1615f0d67db, started, etcd-bootstrap, https://10.1.10.31:2380, https://10.1.10.31:2379
2020-05-14T04:56:02.743273696Z memberDir /var/lib/etcd/member is present on nuc3.redpill.nz
2020-05-14T04:56:02.750948567Z #### attempt 0
2020-05-14T04:56:02.751779911Z       member={name="nuc4.redpill.nz", peerURLs=[https://10.1.10.4:2380}, clientURLs=[https://10.1.10.4:2379]
2020-05-14T04:56:02.751779911Z       member={name="", peerURLs=[https://10.1.10.3:2380}, …
```

Bug 1814576: make evaluation of targetMember strict

---

openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go

`discover-etcd-initial-cluster` will fail without an error if the member has not been added to the cluster before etcd starts.
```
47c2911fa3f192a1, started, etcd-bootstrap, https://192.168.1.239:2380, https://192.168.1.239:2379, false
6eac2c0354f41bcb, started, wj45uos929a-4qdsw-master-2, https://192.168.1.29:2380, https://192.168.1.29:2379, false
8b25c3c3bdeb7654, started, wj45uos929a-4qdsw-master-1, https://192.168.1.11:2380, https://192.168.1.11:2379, false
member={name="etcd-bootstrap", peerURLs=[https://192.168.1.239:2380}, clientURLs=[https://192.168.1.239:2379]
member={name="wj45uos929a-4qdsw-master-2", peerURLs=[https://192.168.1.29:2380}, clientURLs=[https://192.168.1.29:2379]
member={name="wj45uos929a-4qdsw-master-1", peerURLs=[https://192.168.1.11:2380}, …
```

Bug 1883772: discover-etcd-initial-cluster: improve error handling when we dont scale member

---

Dockerfile.rhel

Updating ose-etcd builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/ose-etcd.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.

Bug 1878163: Updating ose-etcd builder & base images to be consistent with ART

---

Dockerfile.rhel

Updating ose-etcd builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-etcd.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-etcd builder & base images to be consistent with ART

---

embed/etcd.go

oversight on the backport, zap logger is not yet the default for release-3.4 so it must be checked before use,

UPSTREAM: <carry>: *: ensure zap logger is set before use

---

bill-of-materials.json
embed/config.go
embed/config_logging.go
embed/config_test.go
etcdmain/config.go
etcdmain/help.go
go.mod
go.sum
vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE
vendor/gopkg.in/natefinch/lumberjack.v2/chown.go
vendor/gopkg.in/natefinch/lumberjack.v2/chown_linux.go
vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go

Manual cherry-pick of https://github.com/etcd-io/etcd/pull/12774 into openshift-4.8

Bug 1958405: UPSTREAM: <carry>: server: add support for log rotation (#12774)

---

embed/etcd.go
etcdmain/grpc_proxy.go
etcdserver/api/etcdhttp/base.go
etcdserver/api/etcdhttp/metrics.go
etcdserver/api/v2http/client.go
proxy/grpcproxy/health.go

manual cherry-pick of https://github.com/etcd-io/etcd/pull/11704 into openshift-4.8
Health check reporting Before
```
2021-05-11 20:55:27.862866 I | etcdserver/api/etcdhttp: /health OK (status code 200)
```
After
```
{"level":"info","ts":"2021-05-12T00:21:55.349Z","caller":"etcdhttp/metrics.go:127","msg":"serving /health true"}
{"level":"info","ts":"2021-05-12T00:21:55.350Z","caller":"etcdhttp/metrics.go:65","msg":"/health OK","status-code":200}
```
This is of course too verbose which is why we need #80 
The end goal will be providing a machine consumable etcd log which is persisted to the host and then rotated in the same fashion that audit logs for kube-apiserver work today. By ensuring healtch checks are taken at a 1s granularity and failures reported we can ensure with great precision …

Bug 1958405: UPSTREAM: <carry>: *: log server-side /health checks

---

embed/etcd.go
etcdmain/grpc_proxy.go
etcdserver/api/etcdhttp/base.go
etcdserver/api/etcdhttp/metrics.go
etcdserver/api/v2http/client.go
proxy/grpcproxy/health.go

Manual cherry-pick of https://github.com/etcd-io/etcd/pull/12677 into openshift-4.8 on top of #79 
net change here is the reduction of verbosity from #79 success checks to debug

Bug 1958405: UPSTREAM: <carry>: etcdserver/api/etcdhttp: log successful etcd server side health check in debug level

---

openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster_test.go

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

Bug 1958913: discover-etcd-initial-cluster: retry if member is not part of member list and dataDir exists

---

etcdctl/ctlv3/command/check.go

This is often used by both support and end users, which causes
etcd to get load sometimes in live production env.
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Bug 1994986: (CARRY) etcdctl/ctlv3/ctl.go: Remove check perf command
